[project]
name = "condorgame-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "densitypdf>=0.1.4",
    "fastapi>=0.121.3",
    "model-runner-client>=0.10.0",
    "numpy>=2.3.4",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
]
