[project]
name = "falcon2-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "densitypdf>=0.1.4",
    "model-runner-client>=0.9.0",
    "numpy>=2.3.4",
    "psycopg2-binary>=2.9.11",
    "redis>=7.0.1",
    "requests>=2.32.5",
    "sqlmodel>=0.0.27",
]