[project]
name = "condorgame-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "densitypdf>=0.1.4",
    "fastapi>=0.121.3",
    #"model-runner-client>=0.9.0",
    "model-runner-client @ git+https://github.com/crunchdao/model-runner-client.git@feat/timeout-per-call",
    "numpy>=2.3.4",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
]
[tool.setuptools.packages.find]
include=["condorgame_backend"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
