logging:
  level: debug

infrastructure:
  database:
    type: sqlite
    path: "/app/data/orchestrator.dev.db"

  publishers:
    - type: websocket
      address: "0.0.0.0"
      port: 9091

  runner:
    type: local
    docker-network-name: "${DOCKER_NETWORK_NAME}"
    submission-storage-path-format: "/app/data/submissions/{id}"
    resource-storage-path-format: "/app/data/models/{id}"

watcher:
  interval: 1
  poller:
    type: yaml
    path: "/app/data/models.dev.yml"

crunches:
  - id: "starter-challenge"
    name: "starter-challenge"
    infrastructure:
      zone: "local"

can-place-in-quarantine: false
use-augmented-info: false
