logging:
  # Logging levels: 'debug', 'trace', 'info', 'warn', 'error'
  level: debug

infrastructure:

  # Configure the database (only one)
  database:
    # Data store type, only `sqlite` available for the moment
    type: sqlite

    # Path of the .db file
    path: "/app/data/orchestrator.dev.db"

  # Configure publishers
  publishers:
    - type: websocket

      # IP address to bind to
      address: "0.0.0.0"

      # Port to bind to
      port: 9091

  # Configure a local builder and runner (only one)
  runner:
    type: local

    # Docker (compose) network name, only if running from a docker container
    docker-network-name: "${DOCKER_NETWORK_NAME}"

    # Directory path format where the submission content are stored
    submission-storage-path-format: "/app/data/submissions/{id}"

    # Directory path format where the resource content are stored
    resource-storage-path-format: "/app/data/models/{id}"

# Configure the watcher
watcher:

  # Check interval, in seconds
  interval: 10

  # Configure the local yaml file model state poller (only one)
  poller:
    type: yaml

    # File path of the file to watch
    path: "/app/config/models.dev.yml"

crunches:
  - id: "condorgame"
    name: "condorgame"
    infrastructure:
      zone: "local"

# Disable the quarantine system
can-place-in-quarantine: false

# Disable fetch model information from Tournament API
use-augmented-info: false
