models:
- id: '1'

    # submission code id, it is the code used to run the model
    # the corresponding directory must exist in the storage
  submission_id: starter-benchmarktracker

    # which crunch this model must be run on
  crunch_id: starter-challenge

    # which desired state this model must be in: "RUNNING", "STOPPED"
  desired_state: RUNNING

  model_name: light
  cruncher_name: degu
  cruncher_id: AHgm2bE4rcyiD1skgvWaujXyyzcfouiq8JXdMKvPhFFR
